// Include generated protobuf code
pub mod file_transfer {
    // This will be generated by build.rs
    tonic::include_proto!("file_transfer");
}

pub mod service;

pub use file_transfer::*;
pub use service::FileTransferServiceImpl;
